# Generated by Django 4.2.3 on 2023-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(db_column='final', max_length=40)),
            ],
            options={
                'db_table': 'configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('codigo', models.TextField(db_column='Codigo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'planes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Todas',
            fields=[
                ('codigo', models.TextField(db_column='Codigo', primary_key=True, serialize=False)),
                ('nombre', models.TextField(db_column='Nombre', max_length=90)),
                ('correlativas', models.TextField(blank=True, db_column='Correlativas', max_length=70, null=True)),
                ('area', models.TextField(blank=True, db_column='Area', default='-', max_length=50, null=True)),
                ('subarea', models.TextField(blank=True, db_column='SubArea', default='-', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', default='-', null=True)),
                ('semestre', models.TextField(blank=True, db_column='Semestre', null=True)),
                ('cursando', models.BooleanField(db_column='Cursando')),
                ('cursada', models.BooleanField(db_column='Cursada')),
                ('final', models.BooleanField(db_column='Final')),
            ],
            options={
                'db_table': 'todas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aprobadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cursando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
    ]
